// <auto-generated />
using System;
using KuaforWebSitesi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KuaforWebSitesi.Migrations
{
    [DbContext(typeof(KuaforDBContext))]
    [Migration("20241219215156_Hizmetler")]
    partial class Hizmetler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KuaforWebSitesi.Models.Calisan", b =>
                {
                    b.Property<int>("CalisanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalisanID"));

                    b.Property<string>("CalisanAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalisanMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalisanSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalisanSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalisanTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CalisanID");

                    b.ToTable("Calisanlar");

                    b.HasData(
                        new
                        {
                            CalisanID = 1,
                            CalisanAd = "Dilan",
                            CalisanMail = "dilan.kaya@shineLab.com",
                            CalisanSifre = "Dilan123",
                            CalisanSoyad = "Kaya",
                            CalisanTelefon = "05395456751"
                        },
                        new
                        {
                            CalisanID = 2,
                            CalisanAd = "Elif",
                            CalisanMail = "elif.yilmaz@shineLab.com",
                            CalisanSifre = "Elif123",
                            CalisanSoyad = "Yılmaz",
                            CalisanTelefon = "05395456752"
                        },
                        new
                        {
                            CalisanID = 3,
                            CalisanAd = "Şeyma",
                            CalisanMail = "seyma.cetin@shineLab.com",
                            CalisanSifre = "Seyma123",
                            CalisanSoyad = "Çetin",
                            CalisanTelefon = "05395456753"
                        },
                        new
                        {
                            CalisanID = 4,
                            CalisanAd = "Ece",
                            CalisanMail = "ece.tuncer@shineLab.com",
                            CalisanSifre = "Ece123",
                            CalisanSoyad = "Tuncer",
                            CalisanTelefon = "05395456754"
                        },
                        new
                        {
                            CalisanID = 5,
                            CalisanAd = "Aslı",
                            CalisanMail = "asli.sahin@shineLab.com",
                            CalisanSifre = "ShineLaB",
                            CalisanSoyad = "Şahin",
                            CalisanTelefon = "05395456755"
                        },
                        new
                        {
                            CalisanID = 6,
                            CalisanAd = "Ceyda",
                            CalisanMail = "ceyda.ozdemir@shineLab.com",
                            CalisanSifre = "Ceyda123",
                            CalisanSoyad = "Özdemir",
                            CalisanTelefon = "05395456756"
                        },
                        new
                        {
                            CalisanID = 7,
                            CalisanAd = "Nisan",
                            CalisanMail = "nisan.kaya@shineLab.com",
                            CalisanSifre = "Nisan123",
                            CalisanSoyad = "Kaya",
                            CalisanTelefon = "05395456757"
                        });
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.CalisanGun", b =>
                {
                    b.Property<int>("CalisanID")
                        .HasColumnType("int");

                    b.Property<int>("GunID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<int>("CalisanGunID")
                        .HasColumnType("int");

                    b.HasKey("CalisanID", "GunID");

                    b.HasIndex("GunID");

                    b.ToTable("CalisanGunler");

                    b.HasData(
                        new
                        {
                            CalisanID = 1,
                            GunID = 1,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 1
                        },
                        new
                        {
                            CalisanID = 1,
                            GunID = 5,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 2
                        },
                        new
                        {
                            CalisanID = 2,
                            GunID = 2,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 3
                        },
                        new
                        {
                            CalisanID = 2,
                            GunID = 3,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 4
                        },
                        new
                        {
                            CalisanID = 2,
                            GunID = 4,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 5
                        },
                        new
                        {
                            CalisanID = 2,
                            GunID = 5,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 6
                        },
                        new
                        {
                            CalisanID = 2,
                            GunID = 6,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 7
                        },
                        new
                        {
                            CalisanID = 3,
                            GunID = 1,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 8
                        },
                        new
                        {
                            CalisanID = 3,
                            GunID = 3,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 9
                        },
                        new
                        {
                            CalisanID = 3,
                            GunID = 5,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 10
                        },
                        new
                        {
                            CalisanID = 3,
                            GunID = 6,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 11
                        },
                        new
                        {
                            CalisanID = 4,
                            GunID = 1,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 12
                        },
                        new
                        {
                            CalisanID = 4,
                            GunID = 2,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 13
                        },
                        new
                        {
                            CalisanID = 4,
                            GunID = 5,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 14
                        },
                        new
                        {
                            CalisanID = 4,
                            GunID = 6,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 15
                        },
                        new
                        {
                            CalisanID = 5,
                            GunID = 1,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 16
                        },
                        new
                        {
                            CalisanID = 5,
                            GunID = 5,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 17
                        },
                        new
                        {
                            CalisanID = 5,
                            GunID = 7,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 18
                        },
                        new
                        {
                            CalisanID = 6,
                            GunID = 2,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 19
                        },
                        new
                        {
                            CalisanID = 6,
                            GunID = 3,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 20
                        },
                        new
                        {
                            CalisanID = 6,
                            GunID = 5,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 21
                        },
                        new
                        {
                            CalisanID = 6,
                            GunID = 6,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 22
                        },
                        new
                        {
                            CalisanID = 6,
                            GunID = 7,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 23
                        },
                        new
                        {
                            CalisanID = 7,
                            GunID = 1,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 24
                        },
                        new
                        {
                            CalisanID = 7,
                            GunID = 3,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 25
                        },
                        new
                        {
                            CalisanID = 7,
                            GunID = 4,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 26
                        },
                        new
                        {
                            CalisanID = 7,
                            GunID = 7,
                            BaslangicSaati = new TimeSpan(0, 0, 0, 0, 0),
                            BitisSaati = new TimeSpan(0, 0, 0, 0, 0),
                            CalisanGunID = 27
                        });
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.CalisanHizmetler", b =>
                {
                    b.Property<int>("CalisanHizmetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalisanHizmetID"));

                    b.Property<int>("CalisanID")
                        .HasColumnType("int");

                    b.Property<int>("HizmetID")
                        .HasColumnType("int");

                    b.HasKey("CalisanHizmetID");

                    b.HasIndex("CalisanID");

                    b.HasIndex("HizmetID");

                    b.ToTable("CalisanHizmetler");

                    b.HasData(
                        new
                        {
                            CalisanHizmetID = 1,
                            CalisanID = 1,
                            HizmetID = 1
                        },
                        new
                        {
                            CalisanHizmetID = 2,
                            CalisanID = 1,
                            HizmetID = 2
                        },
                        new
                        {
                            CalisanHizmetID = 3,
                            CalisanID = 1,
                            HizmetID = 3
                        },
                        new
                        {
                            CalisanHizmetID = 4,
                            CalisanID = 1,
                            HizmetID = 4
                        },
                        new
                        {
                            CalisanHizmetID = 5,
                            CalisanID = 1,
                            HizmetID = 5
                        },
                        new
                        {
                            CalisanHizmetID = 6,
                            CalisanID = 1,
                            HizmetID = 6
                        },
                        new
                        {
                            CalisanHizmetID = 7,
                            CalisanID = 1,
                            HizmetID = 7
                        },
                        new
                        {
                            CalisanHizmetID = 8,
                            CalisanID = 1,
                            HizmetID = 8
                        },
                        new
                        {
                            CalisanHizmetID = 9,
                            CalisanID = 1,
                            HizmetID = 9
                        },
                        new
                        {
                            CalisanHizmetID = 10,
                            CalisanID = 1,
                            HizmetID = 10
                        },
                        new
                        {
                            CalisanHizmetID = 11,
                            CalisanID = 1,
                            HizmetID = 11
                        },
                        new
                        {
                            CalisanHizmetID = 12,
                            CalisanID = 1,
                            HizmetID = 12
                        },
                        new
                        {
                            CalisanHizmetID = 13,
                            CalisanID = 1,
                            HizmetID = 13
                        },
                        new
                        {
                            CalisanHizmetID = 14,
                            CalisanID = 1,
                            HizmetID = 14
                        },
                        new
                        {
                            CalisanHizmetID = 15,
                            CalisanID = 1,
                            HizmetID = 15
                        },
                        new
                        {
                            CalisanHizmetID = 16,
                            CalisanID = 1,
                            HizmetID = 16
                        },
                        new
                        {
                            CalisanHizmetID = 17,
                            CalisanID = 2,
                            HizmetID = 1
                        },
                        new
                        {
                            CalisanHizmetID = 18,
                            CalisanID = 2,
                            HizmetID = 2
                        },
                        new
                        {
                            CalisanHizmetID = 19,
                            CalisanID = 2,
                            HizmetID = 3
                        },
                        new
                        {
                            CalisanHizmetID = 20,
                            CalisanID = 2,
                            HizmetID = 4
                        },
                        new
                        {
                            CalisanHizmetID = 21,
                            CalisanID = 2,
                            HizmetID = 5
                        },
                        new
                        {
                            CalisanHizmetID = 22,
                            CalisanID = 2,
                            HizmetID = 6
                        },
                        new
                        {
                            CalisanHizmetID = 23,
                            CalisanID = 2,
                            HizmetID = 7
                        },
                        new
                        {
                            CalisanHizmetID = 24,
                            CalisanID = 2,
                            HizmetID = 8
                        },
                        new
                        {
                            CalisanHizmetID = 25,
                            CalisanID = 2,
                            HizmetID = 9
                        },
                        new
                        {
                            CalisanHizmetID = 26,
                            CalisanID = 2,
                            HizmetID = 10
                        },
                        new
                        {
                            CalisanHizmetID = 27,
                            CalisanID = 2,
                            HizmetID = 11
                        },
                        new
                        {
                            CalisanHizmetID = 28,
                            CalisanID = 2,
                            HizmetID = 12
                        },
                        new
                        {
                            CalisanHizmetID = 29,
                            CalisanID = 2,
                            HizmetID = 13
                        },
                        new
                        {
                            CalisanHizmetID = 30,
                            CalisanID = 2,
                            HizmetID = 14
                        },
                        new
                        {
                            CalisanHizmetID = 31,
                            CalisanID = 2,
                            HizmetID = 15
                        },
                        new
                        {
                            CalisanHizmetID = 32,
                            CalisanID = 2,
                            HizmetID = 16
                        },
                        new
                        {
                            CalisanHizmetID = 33,
                            CalisanID = 3,
                            HizmetID = 1
                        },
                        new
                        {
                            CalisanHizmetID = 34,
                            CalisanID = 3,
                            HizmetID = 2
                        },
                        new
                        {
                            CalisanHizmetID = 35,
                            CalisanID = 3,
                            HizmetID = 3
                        },
                        new
                        {
                            CalisanHizmetID = 36,
                            CalisanID = 3,
                            HizmetID = 4
                        },
                        new
                        {
                            CalisanHizmetID = 37,
                            CalisanID = 3,
                            HizmetID = 5
                        },
                        new
                        {
                            CalisanHizmetID = 38,
                            CalisanID = 3,
                            HizmetID = 6
                        },
                        new
                        {
                            CalisanHizmetID = 39,
                            CalisanID = 3,
                            HizmetID = 7
                        },
                        new
                        {
                            CalisanHizmetID = 40,
                            CalisanID = 3,
                            HizmetID = 8
                        },
                        new
                        {
                            CalisanHizmetID = 41,
                            CalisanID = 3,
                            HizmetID = 9
                        },
                        new
                        {
                            CalisanHizmetID = 42,
                            CalisanID = 3,
                            HizmetID = 10
                        },
                        new
                        {
                            CalisanHizmetID = 43,
                            CalisanID = 3,
                            HizmetID = 11
                        },
                        new
                        {
                            CalisanHizmetID = 44,
                            CalisanID = 3,
                            HizmetID = 12
                        },
                        new
                        {
                            CalisanHizmetID = 45,
                            CalisanID = 3,
                            HizmetID = 13
                        },
                        new
                        {
                            CalisanHizmetID = 46,
                            CalisanID = 3,
                            HizmetID = 14
                        },
                        new
                        {
                            CalisanHizmetID = 47,
                            CalisanID = 4,
                            HizmetID = 1
                        },
                        new
                        {
                            CalisanHizmetID = 48,
                            CalisanID = 4,
                            HizmetID = 2
                        },
                        new
                        {
                            CalisanHizmetID = 49,
                            CalisanID = 4,
                            HizmetID = 3
                        },
                        new
                        {
                            CalisanHizmetID = 50,
                            CalisanID = 4,
                            HizmetID = 4
                        },
                        new
                        {
                            CalisanHizmetID = 51,
                            CalisanID = 4,
                            HizmetID = 5
                        },
                        new
                        {
                            CalisanHizmetID = 52,
                            CalisanID = 4,
                            HizmetID = 6
                        },
                        new
                        {
                            CalisanHizmetID = 53,
                            CalisanID = 4,
                            HizmetID = 7
                        },
                        new
                        {
                            CalisanHizmetID = 54,
                            CalisanID = 4,
                            HizmetID = 8
                        },
                        new
                        {
                            CalisanHizmetID = 55,
                            CalisanID = 4,
                            HizmetID = 9
                        },
                        new
                        {
                            CalisanHizmetID = 56,
                            CalisanID = 4,
                            HizmetID = 10
                        },
                        new
                        {
                            CalisanHizmetID = 57,
                            CalisanID = 4,
                            HizmetID = 11
                        },
                        new
                        {
                            CalisanHizmetID = 58,
                            CalisanID = 4,
                            HizmetID = 12
                        },
                        new
                        {
                            CalisanHizmetID = 59,
                            CalisanID = 4,
                            HizmetID = 13
                        },
                        new
                        {
                            CalisanHizmetID = 60,
                            CalisanID = 4,
                            HizmetID = 14
                        },
                        new
                        {
                            CalisanHizmetID = 61,
                            CalisanID = 4,
                            HizmetID = 15
                        },
                        new
                        {
                            CalisanHizmetID = 62,
                            CalisanID = 4,
                            HizmetID = 16
                        },
                        new
                        {
                            CalisanHizmetID = 63,
                            CalisanID = 4,
                            HizmetID = 17
                        },
                        new
                        {
                            CalisanHizmetID = 64,
                            CalisanID = 4,
                            HizmetID = 18
                        },
                        new
                        {
                            CalisanHizmetID = 65,
                            CalisanID = 4,
                            HizmetID = 19
                        },
                        new
                        {
                            CalisanHizmetID = 66,
                            CalisanID = 4,
                            HizmetID = 20
                        },
                        new
                        {
                            CalisanHizmetID = 67,
                            CalisanID = 4,
                            HizmetID = 21
                        },
                        new
                        {
                            CalisanHizmetID = 68,
                            CalisanID = 4,
                            HizmetID = 22
                        },
                        new
                        {
                            CalisanHizmetID = 69,
                            CalisanID = 4,
                            HizmetID = 23
                        },
                        new
                        {
                            CalisanHizmetID = 70,
                            CalisanID = 4,
                            HizmetID = 24
                        },
                        new
                        {
                            CalisanHizmetID = 71,
                            CalisanID = 5,
                            HizmetID = 1
                        },
                        new
                        {
                            CalisanHizmetID = 72,
                            CalisanID = 5,
                            HizmetID = 2
                        },
                        new
                        {
                            CalisanHizmetID = 73,
                            CalisanID = 5,
                            HizmetID = 3
                        },
                        new
                        {
                            CalisanHizmetID = 74,
                            CalisanID = 5,
                            HizmetID = 4
                        },
                        new
                        {
                            CalisanHizmetID = 75,
                            CalisanID = 5,
                            HizmetID = 5
                        },
                        new
                        {
                            CalisanHizmetID = 76,
                            CalisanID = 6,
                            HizmetID = 17
                        },
                        new
                        {
                            CalisanHizmetID = 77,
                            CalisanID = 6,
                            HizmetID = 18
                        },
                        new
                        {
                            CalisanHizmetID = 78,
                            CalisanID = 6,
                            HizmetID = 19
                        },
                        new
                        {
                            CalisanHizmetID = 79,
                            CalisanID = 6,
                            HizmetID = 20
                        },
                        new
                        {
                            CalisanHizmetID = 80,
                            CalisanID = 6,
                            HizmetID = 21
                        },
                        new
                        {
                            CalisanHizmetID = 81,
                            CalisanID = 6,
                            HizmetID = 22
                        },
                        new
                        {
                            CalisanHizmetID = 82,
                            CalisanID = 6,
                            HizmetID = 23
                        },
                        new
                        {
                            CalisanHizmetID = 83,
                            CalisanID = 6,
                            HizmetID = 24
                        },
                        new
                        {
                            CalisanHizmetID = 84,
                            CalisanID = 7,
                            HizmetID = 17
                        },
                        new
                        {
                            CalisanHizmetID = 85,
                            CalisanID = 7,
                            HizmetID = 18
                        },
                        new
                        {
                            CalisanHizmetID = 86,
                            CalisanID = 7,
                            HizmetID = 19
                        },
                        new
                        {
                            CalisanHizmetID = 87,
                            CalisanID = 7,
                            HizmetID = 20
                        },
                        new
                        {
                            CalisanHizmetID = 88,
                            CalisanID = 7,
                            HizmetID = 21
                        },
                        new
                        {
                            CalisanHizmetID = 89,
                            CalisanID = 7,
                            HizmetID = 22
                        },
                        new
                        {
                            CalisanHizmetID = 90,
                            CalisanID = 7,
                            HizmetID = 23
                        },
                        new
                        {
                            CalisanHizmetID = 91,
                            CalisanID = 7,
                            HizmetID = 24
                        });
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.Gunler", b =>
                {
                    b.Property<int>("GunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GunID"));

                    b.Property<string>("GunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GunID");

                    b.ToTable("Gunler");

                    b.HasData(
                        new
                        {
                            GunID = 1,
                            GunAdi = "Pazartesi"
                        },
                        new
                        {
                            GunID = 2,
                            GunAdi = "Salı"
                        },
                        new
                        {
                            GunID = 3,
                            GunAdi = "Çarşamba"
                        },
                        new
                        {
                            GunID = 4,
                            GunAdi = "Perşembe"
                        },
                        new
                        {
                            GunID = 5,
                            GunAdi = "Cuma"
                        },
                        new
                        {
                            GunID = 6,
                            GunAdi = "Cumartesi"
                        },
                        new
                        {
                            GunID = 7,
                            GunAdi = "Pazar"
                        });
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.HizmetKategori", b =>
                {
                    b.Property<int>("HizmetKategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HizmetKategoriID"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HizmetKategoriID");

                    b.ToTable("HizmetKategoriler");

                    b.HasData(
                        new
                        {
                            HizmetKategoriID = 1,
                            KategoriAdi = "Saç Kesimi"
                        },
                        new
                        {
                            HizmetKategoriID = 2,
                            KategoriAdi = "Saç Bakımı"
                        },
                        new
                        {
                            HizmetKategoriID = 3,
                            KategoriAdi = "Manikür"
                        },
                        new
                        {
                            HizmetKategoriID = 4,
                            KategoriAdi = "Pedikür"
                        },
                        new
                        {
                            HizmetKategoriID = 5,
                            KategoriAdi = "Gelin"
                        });
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.Hizmetler", b =>
                {
                    b.Property<int>("HizmetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HizmetID"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HizmetAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HizmetKategoriID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Sure")
                        .HasColumnType("time");

                    b.HasKey("HizmetID");

                    b.HasIndex("HizmetKategoriID");

                    b.ToTable("Hizmetler");

                    b.HasData(
                        new
                        {
                            HizmetID = 1,
                            Fiyat = 400m,
                            HizmetAdi = "Fön",
                            HizmetKategoriID = 2,
                            Sure = new TimeSpan(0, 1, 0, 0, 0)
                        },
                        new
                        {
                            HizmetID = 2,
                            Fiyat = 800m,
                            HizmetAdi = "Maşa",
                            HizmetKategoriID = 2,
                            Sure = new TimeSpan(0, 1, 0, 0, 0)
                        },
                        new
                        {
                            HizmetID = 3,
                            Fiyat = 1000m,
                            HizmetAdi = "Örgü",
                            HizmetKategoriID = 2,
                            Sure = new TimeSpan(0, 1, 0, 0, 0)
                        },
                        new
                        {
                            HizmetID = 4,
                            Fiyat = 1200m,
                            HizmetAdi = "Topuz",
                            HizmetKategoriID = 2,
                            Sure = new TimeSpan(0, 1, 0, 0, 0)
                        },
                        new
                        {
                            HizmetID = 5,
                            Fiyat = 1300m,
                            HizmetAdi = "Saç Kesim",
                            HizmetKategoriID = 2,
                            Sure = new TimeSpan(0, 1, 0, 0, 0)
                        },
                        new
                        {
                            HizmetID = 6,
                            Fiyat = 2500m,
                            HizmetAdi = "Cila",
                            HizmetKategoriID = 1,
                            Sure = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            HizmetID = 7,
                            Fiyat = 1250m,
                            HizmetAdi = "Dip Boya",
                            HizmetKategoriID = 1,
                            Sure = new TimeSpan(0, 1, 0, 0, 0)
                        },
                        new
                        {
                            HizmetID = 8,
                            Fiyat = 1750m,
                            HizmetAdi = "Transparan Boya",
                            HizmetKategoriID = 1,
                            Sure = new TimeSpan(0, 1, 0, 0, 0)
                        },
                        new
                        {
                            HizmetID = 9,
                            Fiyat = 2500m,
                            HizmetAdi = "Bütün Boya",
                            HizmetKategoriID = 1,
                            Sure = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            HizmetID = 10,
                            Fiyat = 5500m,
                            HizmetAdi = "Brushlight",
                            HizmetKategoriID = 1,
                            Sure = new TimeSpan(0, 3, 0, 0, 0)
                        },
                        new
                        {
                            HizmetID = 11,
                            Fiyat = 6000m,
                            HizmetAdi = "Highlight",
                            HizmetKategoriID = 1,
                            Sure = new TimeSpan(0, 5, 0, 0, 0)
                        },
                        new
                        {
                            HizmetID = 12,
                            Fiyat = 8000m,
                            HizmetAdi = "Röfle",
                            HizmetKategoriID = 1,
                            Sure = new TimeSpan(0, 5, 0, 0, 0)
                        },
                        new
                        {
                            HizmetID = 13,
                            Fiyat = 4000m,
                            HizmetAdi = "Sakinleştirici Bakım",
                            HizmetKategoriID = 1,
                            Sure = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            HizmetID = 14,
                            Fiyat = 6000m,
                            HizmetAdi = "Düzleştirici Bakım",
                            HizmetKategoriID = 1,
                            Sure = new TimeSpan(0, 2, 30, 0, 0)
                        },
                        new
                        {
                            HizmetID = 15,
                            Fiyat = 6000m,
                            HizmetAdi = "Gelin Saçı",
                            HizmetKategoriID = 5,
                            Sure = new TimeSpan(0, 3, 0, 0, 0)
                        },
                        new
                        {
                            HizmetID = 16,
                            Fiyat = 6000m,
                            HizmetAdi = "Gelin Makyajı",
                            HizmetKategoriID = 5,
                            Sure = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            HizmetID = 17,
                            Fiyat = 750m,
                            HizmetAdi = "Manikür",
                            HizmetKategoriID = 3,
                            Sure = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            HizmetID = 18,
                            Fiyat = 750m,
                            HizmetAdi = "Pedikür",
                            HizmetKategoriID = 3,
                            Sure = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            HizmetID = 19,
                            Fiyat = 550m,
                            HizmetAdi = "El Kalıcı Oje",
                            HizmetKategoriID = 3,
                            Sure = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            HizmetID = 20,
                            Fiyat = 750m,
                            HizmetAdi = "Ayak Kalıcı Oje",
                            HizmetKategoriID = 3,
                            Sure = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            HizmetID = 21,
                            Fiyat = 2500m,
                            HizmetAdi = "Profesyonel Cilt Bakımı",
                            HizmetKategoriID = 4,
                            Sure = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            HizmetID = 22,
                            Fiyat = 400m,
                            HizmetAdi = "Kaş Alımı",
                            HizmetKategoriID = 4,
                            Sure = new TimeSpan(0, 0, 20, 0, 0)
                        },
                        new
                        {
                            HizmetID = 23,
                            Fiyat = 1250m,
                            HizmetAdi = "Kirpik Lifting",
                            HizmetKategoriID = 4,
                            Sure = new TimeSpan(0, 0, 45, 0, 0)
                        },
                        new
                        {
                            HizmetID = 24,
                            Fiyat = 1500m,
                            HizmetAdi = "Karbon Peeling",
                            HizmetKategoriID = 4,
                            Sure = new TimeSpan(0, 0, 45, 0, 0)
                        });
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriID"));

                    b.Property<string>("MusteriAd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MusteriMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MusteriSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MusteriID");

                    b.HasIndex("MusteriMail")
                        .IsUnique();

                    b.HasIndex("MusteriTelefon")
                        .IsUnique();

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.MusteriRol", b =>
                {
                    b.Property<int>("MusteriRolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriRolID"));

                    b.Property<int>("MusteriID")
                        .HasColumnType("int");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.HasKey("MusteriRolID");

                    b.HasIndex("MusteriID");

                    b.HasIndex("RolID");

                    b.ToTable("MusteriRoller");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.Randevu", b =>
                {
                    b.Property<int>("RandevuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuID"));

                    b.Property<int>("CalisanID")
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HizmetID")
                        .HasColumnType("int");

                    b.Property<int>("MusteriID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("time");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("RandevuID");

                    b.HasIndex("CalisanID");

                    b.HasIndex("HizmetID");

                    b.HasIndex("MusteriID");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolID");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.CalisanGun", b =>
                {
                    b.HasOne("KuaforWebSitesi.Models.Calisan", "Calisanlar")
                        .WithMany("CalisanGunler")
                        .HasForeignKey("CalisanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuaforWebSitesi.Models.Gunler", "Gunler")
                        .WithMany("CalisanGunler")
                        .HasForeignKey("GunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisanlar");

                    b.Navigation("Gunler");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.CalisanHizmetler", b =>
                {
                    b.HasOne("KuaforWebSitesi.Models.Calisan", "Calisan")
                        .WithMany("CalisanHizmetler")
                        .HasForeignKey("CalisanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuaforWebSitesi.Models.Hizmetler", "Hizmet")
                        .WithMany("CalisanHizmetler")
                        .HasForeignKey("HizmetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Hizmet");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.Hizmetler", b =>
                {
                    b.HasOne("KuaforWebSitesi.Models.HizmetKategori", "HizmetKategoriler")
                        .WithMany("Hizmetler")
                        .HasForeignKey("HizmetKategoriID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HizmetKategoriler");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.MusteriRol", b =>
                {
                    b.HasOne("KuaforWebSitesi.Models.Musteri", "Musteri")
                        .WithMany("MusteriRoller")
                        .HasForeignKey("MusteriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuaforWebSitesi.Models.Rol", "Rol")
                        .WithMany("MusteriRoller")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.Randevu", b =>
                {
                    b.HasOne("KuaforWebSitesi.Models.Calisan", "Calisan")
                        .WithMany("Randevular")
                        .HasForeignKey("CalisanID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KuaforWebSitesi.Models.Hizmetler", "Hizmetler")
                        .WithMany("Randevular")
                        .HasForeignKey("HizmetID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KuaforWebSitesi.Models.Musteri", "Musteri")
                        .WithMany("Randevular")
                        .HasForeignKey("MusteriID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Hizmetler");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.Calisan", b =>
                {
                    b.Navigation("CalisanGunler");

                    b.Navigation("CalisanHizmetler");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.Gunler", b =>
                {
                    b.Navigation("CalisanGunler");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.HizmetKategori", b =>
                {
                    b.Navigation("Hizmetler");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.Hizmetler", b =>
                {
                    b.Navigation("CalisanHizmetler");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.Musteri", b =>
                {
                    b.Navigation("MusteriRoller");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("KuaforWebSitesi.Models.Rol", b =>
                {
                    b.Navigation("MusteriRoller");
                });
#pragma warning restore 612, 618
        }
    }
}
